### ISSUE TITLE
Beta release

### ISSUE THREAD

**Issue by Michael21107** [bttfv/BackToTheFutureV#31]
any chance for a beta release for compatibility with SHVDN 3.6?

**Comment by nomakewan** [comment]
Considering the significant time it is taking for SHVDN 3.7.0 to come out (plus several blocking issues in the current dev release that would preclude a release of 2.4.0 anyway) we are considering releasing a "stopgap" 2.3.3 which would include compatibility with SHVDN 3.6.0 and LemonUI 2.0. In essence it would just be 2.3.2 but with a few fixes for items that have cropped up in the last few GTAV versions (biggest being our reentry code failing to steer in GTAV v3095 due to a code change for a particular memory location).

I'm going to close this as it is not actually an issue, but as always releases will be found on our GTA5-Mods page. Thank you!

**Comment by Michael21107** [comment]
well there is also a tag _enhancement_ which is for _New feature or request_
